# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '726d051a-fb42-4a99-8dc2-bb3f15906bd8'
  imageRepository: 'junwoojeongspringdemo'
  containerRegistry: 'cr2023.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - upload: $(system.defaultWorkingDirectory)
      artifact: drop    
- stage: Deploy
  displayName: Deploy 
  jobs: 
  - deployment: VMDeploy
    displayName: Deploy
    environment:
      name: test-deploy-to-vm
      resourceType: VirtualMachine  
    strategy:
      runOnce:
        preDeploy:
          steps:
          - download: current
            artifact: drop
          - script: |
              echo initialize, cleanup, backup, install certs

              sudo mkdir -p /etc/apt/keyrings
              curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key \
                | gpg --dearmor \
                | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
                  https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" \
                | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
              sudo apt-get update -qq
              sudo apt-get -qq -y install podman

        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Modify deployment script based on the app type
                echo "Starting deployment script run"
                #sudo killall java 
                #sudo java -jar '$(Pipeline.Workspace)/drop/target/spring-demo-1.0.0.jar' &

                podman pull cr2023.azurecr.io/junwoojeongspringdemo:158
                podman run -p 80:80 cr2023.azurecr.io/junwoojeongspringdemo:158 
