{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "helm-demo.fullname" . }}
  labels: 
    {{- include "helm-demo.labels" . | nindent 4 }}
  annotations:
    'haproxy.router.openshift.io/timeout': '60s'
spec:
  #host: {{ .Values.route.host }}
  path: {{ .Values.route.path }}
  port:
    targetPort: http
  #tls:
  #  insecureEdgeTerminationPolicy: Redirect
  #  termination: edge
  to:
    kind: Service
    name: {{ include "helm-demo.fullname" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None  
  wildcardPolicy: None
{{- end }}