apiVersion : apps/v1
kind: Deployment
metadata:
  name: spring-demo 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
        - name: spring-demo
          image: crfy25.azurecr.io/spring-demo:latest
          ports:
          - containerPort: 80
      #imagePullSecrets:
      #  - name: cr2023f759-auth    
