apiVersion : apps/v1
kind: Deployment
metadata:
  name: junwoojeongspringdemo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: junwoojeongspringdemo
  template:
    metadata:
      labels:
        app: junwoojeongspringdemo 
    spec:
      containers:
        - name: junwoojeongspringdemo 
          #image: cr2023.azurecr.io/junwoojeongspringdemo:210
          image:  ${{ images }}
          ports:
          - containerPort: 80
      #imagePullSecrets:
      #  - name: cr2023f759-auth    
