kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: spring-demo
  namespace: cicd-demo
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 'quay.io/jjeong/spring-demo:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'fuse7-java11-openshift:1.10'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/junw9293/spring-demo.git'
      ref: master
    sourceSecret:
      name: github-pat-secret
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial