apiVersion: v1
kind: Service
metadata:
  name: spring-demo-loadbalancer
spec:
  type: LoadBalancer
  selector:
    deployment: spring-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
